Section "InputClass"
	Identifier "touchpad"
	MatchIsTouchpad "on"
	Driver "libinput"

	Option "Tapping" "on"
	Option "ClickMethod" "clickfinger"
	Option "DisableWhileTyping" "true"
	Option "TappingDrag" "true"
	Option "AccelProfile" "adaptive"
	Option "AccelSpeed" "0.2"
EndSection
