PLATFORM_PROFILE_ON_AC="performance"
PLATFORM_PROFILE_ON_BAT="performance"
NMI_WATCHDOG="1"

SATA_LINKPWR_ON_AC="max_performance"
SATA_LINKPWR_ON_BAT="max_performance"
AHCI_RUNTIME_PM_ON_AC="on"
AHCI_RUNTIME_PM_ON_BAT="on"

PCIE_ASPM_ON_AC="performance"
PCIE_ASPM_ON_BAT="performance"
RUNTIME_PM_ON_AC="on"
RUNTIME_PM_ON_BAT="on"

WIFI_PWR_ON_AC="off"
WIFI_PWR_ON_BAT="off"
WOL_DISABLE="N"
BLUETOOTH_PWR_ON_AC="on"
BLUETOOTH_PWR_ON_BAT="on"

SOUND_POWER_SAVE_ON_AC="0"
SOUND_POWER_SAVE_ON_BAT="0"
AUDIO_POWER_ON_AC="0"
AUDIO_POWER_ON_BAT="0"
USB_AUTOSUSPEND="0"
