#!/bin/bash

declare -r FORMAT_SUCCESS="\e[1;32m[SUCCESS]\e[0m"
declare -r FORMAT_WARNING="\e[1;33m[WARNING]\e[0m"
declare -r FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"

function help() {
	local FORMAT_BOLD="\e[1;34m"
	local FORMAT_RESET="\e[0m"
	echo -e "${FORMAT_BOLD}USAGE:${FORMAT_RESET} $(basename "$0") [OPTIONS] [ARGUMENTS]

${FORMAT_BOLD}DESCRIPTION:${FORMAT_RESET}
    Brief description of what the script does.

${FORMAT_BOLD}ARGUMENTS:${FORMAT_RESET}
    ARG1               Description of the first argument.
    ARG2               Description of the second argument.

${FORMAT_BOLD}OPTIONS:${FORMAT_RESET}
    -s                 Brief description for success flag.
    -w                 Brief description for warning flag.
    -e                 Brief description for error flag.
    -h                 Display this help message.

${FORMAT_BOLD}EXAMPLES:${FORMAT_RESET}
    $(basename "$0") -s arg1
    $(basename "$0") -e -w arg1 arg2"

	return 0
}

function main() {
	while getopts "ewsh" opt; do
		case $opt in
			s) printf "%b Success example for %s\n" "$FORMAT_SUCCESS" "$opt" ;;
			w) printf "%b Warning example for %s\n" "$FORMAT_WARNING" "$opt" ;;
			e) printf "%b Error example for %s\n" "$FORMAT_ERROR" "$opt" ;;
			h) help && exit 0 ;;
			*) printf "%b Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1 ;;
		esac
	done

	printf "Hello World\n"

	return 0
}

main "$@"
