#!/bin/bash

sleep 2

if xrandr | grep -q "HDMI-1 connected" ; then
	xset -dpms
	xset s off
	bspc monitor HDMI-1 -d   
else
	xset +dpms
	xset s 600
	bspc monitor HDMI-1 -r
fi

feh --bg-fill "$HOME/.local/share/wallpaper_actual.png" &
