#!/bin/bash

sourceDesktops=(6 7 8)
targetDesktop=5

for desktop in "${sourceDesktops[@]}"; do
	for wid in $(bspc query -N -d "^$desktop"); do
		bspc node "$wid" --to-desktop "^$targetDesktop"
	done
done
