#!/bin/bash

declare FORMAT_SUCCESS="\e[1;32m[SUCCESS]\e[0m"
declare FORMAT_WARNING="\e[1;33m[WARNING]\e[0m"
declare FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"

function help() {
	local FORMAT_BOLD="\e[1;34m"
	local FORMAT_RESET="\e[0m"
	printf "${FORMAT_BOLD}USAGE:${FORMAT_RESET} %s INPUT_FILE\n" "$(basename "$0")"
	exit 1
}

function main() {
	while getopts "ewsh" opt; do
		case $opt in
			s) printf "%b Success example for %s\n" "$FORMAT_SUCCESS" "$opt" ;;
			w) printf "%b Warning example for %s\n" "$FORMAT_WARNING" "$opt" ;;
			e) printf "%b Error example for %s\n" "$FORMAT_ERROR" "$opt" ;;
			h) help ;;
			*) exit 1 ;;
		esac
	done

	printf "Hello World\n"

	return 0
}

main "$@"
