#!/bin/sh

#! ========================================================================== !#
#!
#!                 ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#!                 ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#!                 ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#!                 ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#!                 ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#!                 ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#!
#!                            - Made by Druxorey -
#!                         https://github.com/druxorey
#!
#! ========================================================================== !#

#* ================================= monitor ================================ *#

bspc monitor eDP-1 -d     
bspc monitor HDMI-1 -d   

#* =========================== startup application ========================== *#

sxhkd &
polybar &
dunst &
picom &
autorandr --change &

feh --bg-fill "$HOME/.local/share/wallpaper_actual.png" &

#* ================================== bspc ================================== *#

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config normal_border_color "#343746"
bspc config active_border_color "#343746"
bspc config focused_border_color "#BD93F9"
bspc config presel_feedback_color "#BD93F9"

bspc rule -a Blueman-manager state=floating center=true
bspc rule -a protonvpn-app state=floating center=true
bspc rule -a "Proton Pass" state=floating center=true
bspc rule -a Qalculate-gtk state=floating center=true
bspc rule -a simple-scan state=floating center=true
bspc rule -a Gloobus-preview state=floating
bspc rule -a Screenkey manage=off

wmname LG3D

#* ================================== init ================================== *#

sudo ln -sf /etc/tlp.d/3-normal.conf /etc/tlp.conf &
sudo tlp start &
