#!/bin/sh

#! ========================================================================== !#
#!
#!                 ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗
#!                 ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║
#!                 ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║
#!                 ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║
#!                 ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║
#!                 ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝
#!
#!                            - Made by Druxorey -
#!                         https://github.com/druxorey
#!
#! ========================================================================== !#

pgrep -x sxhkd > /dev/null || sxhkd &

#* =========================== startup application ========================== *#

feh --bg-fill "$HOME/.local/share/wallpaper_actual.png" &
polybar &
picom --config ~/.config/picom/picom.conf &
setxkbmap us -variant intl &
libinput-gestures-setup start &
thunar --daemon &
dunst &
systemctl --user enable --now clipmenud &

#* ================================= monitor ================================ *#

bspc monitor eDP-1 -d     
bspc monitor HDMI-1 -d   

wmname LG3D
autorandr --change &

#* ================================== bspc ================================== *#

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false

bspc config normal_border_color "#282A36"
bspc config active_border_color "#282A36"
bspc config focused_border_color "#BD93F9"
bspc config presel_feedback_color "#BD93F9"

bspc rule -a Chromium desktop='^2'
bspc rule -a Blueman-manager state=floating center=true
bspc rule -a Protonvpn-app state=floating center=true
bspc rule -a Qalculate-gtk state=floating center=true
bspc rule -a simple-scan state=floating center=true
bspc rule -a Gloobus-preview state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#* ================================== init ================================== *#

# Turn the default tlp config
sudo ln -sf /etc/tlp.d/3-normal.conf /etc/tlp.conf
picom -b --config "$HOME/.config/picom/picom.conf" &
sudo tlp start
