
#! =================================================================== !#
#!
#!                ███████╗███████╗██╗  ██╗██████╗  ██████╗
#!                ╚══███╔╝██╔════╝██║  ██║██╔══██╗██╔════╝
#!                  ███╔╝ ███████╗███████║██████╔╝██║     
#!                 ███╔╝  ╚════██║██╔══██║██╔══██╗██║     
#!                ███████╗███████║██║  ██║██║  ██║╚██████╗
#!                ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝
#!
#!                        - Made by Druxorey -
#!
#!                    https://github.com/druxorey
#!                https://www.reddit.com/user/Druxorey
#! 
#! =================================================================== !#

#* ============================= startup ============================= *#

[[ $- != *i* ]] && return
PS1='[\u@\h \W]\$ '
fastfetch --load-config ~/.config/fastfetch/init.jsonc
echo

eval "$(zoxide init zsh)"
eval "$(thefuck --alias)"
eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/dracula.omp.json)"

#* =========================== path export =========================== *#

export PATH=$PATH:~/.config/bin/
export GIT_EDITOR=nvim

#* ============================= aliases ============================= *#

# directory navigation
alias vim='nvim'
alias cat='bat'
alias ls='eza --icons --group-directories-first'
alias la='eza --icons -a --group-directories-first'
alias lt='eza --icons --tree --group-directories-first'
alias ll='eza --icons -alh --group-directories-first'
alias labc='eza --icons -la'
alias l.='eza -a | grep -E "^\."'
alias cd='z'
alias cdd='z $2 ; ls'
alias cdi='zi'
alias ..='z ..'
alias ...='z ../..'

# shortcuts
alias convert='magick'
alias fk='fuck'
alias cp='cp -i'
alias cpv='rsync -avh --info=progress2'
alias th='trash'
alias thl='trash-list'
alias thr='trash-restore'
alias matrix='cmatrix -C blue'
alias grep='grep --color=auto'
alias peaclock="peaclock --config ~/.config/peaclock"
alias mdtopdf='pandoc $1 -o default.pdf --pdf-engine=xelatex -V mainfont="Arial" monofont="Arial"'

# pacman and yay
alias sysupdate='sudo pacman -Syu ; yay -Sua --noconfirm'
alias unlock='sudo rm /var/lib/pacman/db.lck'

# git
alias gstatus='git status'
alias gadd='git add'
alias grestore='git restore --staged'
alias gcommit='git commit'
alias glog='git log --oneline -n 10'
alias gcheckout='git checkout'
alias gbranch='git branch'
alias gmerge='git merge'
alias gpull='git pull'
alias gpush='git push'

# macros
alias hs='cat ~/.config/zsh/.histfile | fzf'
alias zshrc='nvim ~/.zshrc'
alias dotfiles='cd ~/Workspace/dotfiles/'
alias dotfiles-code='code ~/Workspace/dotfiles/'
alias setkeys="setxkbmap us -variant intl"
alias reload='clear ; source ~/.bashrc ; source ~/.zshrc'
alias wgetm='xargs -n 1 wget --limit-rate=2500k <'
alias yt-audio='yt-dlp -x --audio-format mp3'
alias yt-1080='yt-dlp -f "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]"'
alias yt-720='yt-dlp -f "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]"'
alias yt-480='yt-dlp -f "bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]"'
alias vencord='sh -c "$(curl -sS https://raw.githubusercontent.com/Vendicated/VencordInstaller/main/install.sh)"'

# python
alias py="python3"
alias rm-pychache="sudo rm -r __pycache__"
alias venv-activate='source .venv/bin/activate'
alias venv-requirements='pip freeze > requirements.txt'
alias venv-create='virtualenv .venv'
alias venv-desactivate='deactivate'

# system
alias lock="dm-tool lock"
alias logout="bspc quit"
alias shutdown='shutdown now'
alias monitor-chome='xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode 1600x900 --rotate normal --right-of eDP-1'
alias monitor-dhome='xrandr --output HDMI-1 --off'

#* =============================== zsh =============================== *#

# plugins
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# autocomplete
zstyle :compinstall filename '/home/druxorey/.zshrc'
zstyle ':completion:*' menu select
zstyle ':autocomplete:*' default-context history-incremental-search-backward
_comp_options+=(globdots)
autoload -Uz compinit
compinit

# history
HISTFILE=~/.config/zsh/.histfile
HISTSIZE=10000
SAVEHIST=10000

# vim mode
bindkey -v
export KEYTIMEOUT=1

# key bindings
bindkey "^?"      backward-delete-char
bindkey "^u"      backward-kill-line
bindkey "^a"      beginning-of-line
bindkey "^e"      end-of-line
bindkey "^k"      kill-line
bindkey "^[[3~"   delete-char

# fzf settings
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
export FZF_CTRL_T_OPTS="
  --walker-skip .git,node_modules,target,.local,.steam
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
source <(fzf --zsh)

#* ============================ functions ============================ *#

function rsudo() {
    if [[ $# == 0 ]]; then
        sudo $(history -p '!!')
    else
        sudo "$@"
    fi
}


function compress() {

    [[ "$2" =~ ^[0-9]+$ ]] && set -- "$1" "" "$2"

    local date=$(date +%d-%m-%Y_%H-%M-%S)
    local compressionLevel="${3:-0}"
    local outputFile="${2:-${compressionLevel}_${date}.${1#*.}}"

    case $compressionLevel in
        0) compression=20 ;;
        1) compression=25 ;;
        2) compression=30 ;;
        3) compression=35 ;;
        *) echo "Wrong compression level." ; return ;;
    esac

    ffmpeg -i "$1" -vcodec libx264 -crf $compression "$outputFile"
}


function ex() {
    if [ -f "$1" ] ; then
        case $1 in
            *.tar.bz2)  xjf $1   ;;
            *.tar.gz)   tar xzf $1   ;;
            *.bz2)      bunzip2 $1   ;;
            *.rar)      unrar x $1   ;;
            *.gz)       gunzip $1    ;;
            *.tar)      tar xf $1    ;;
            *.tbz2)     tar xjf $1   ;;
            *.tgz)      tar xzf $1   ;;
            *.zip)      unzip $1     ;;
            *.Z)        uncompress $1;;
            *.7z)       7z x $1      ;;
            *.deb)      ar x $1      ;;
            *.tar.xz)   tar xf $1    ;;
            *.tar.zst)  unzstd $1    ;;
            *) echo "'$1' cannot be extracted via ex()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}


function open() {
    if [ -f "$1" ] ; then
        case $1 in
            *.mp4)      mpv $1     ;;
            *.mkv)      mpv $1     ;;
            *.mp3)      mpv $1     ;;
            *.avi)      mpv $1     ;;
            *.flac)     mpv $1     ;;
            *.png)      sxiv $1    ;;
            *.webp)     sxiv $1    ;;
            *.jpeg)     sxiv $1    ;;
            *.jpg)      sxiv $1    ;;
            *.pdf)      zathura $1 ;;
            *) echo "'$1' cannot be open via open()\n Use: [mpv, sxiv or zathura]" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}
