
#! ========================================================================== !#
#!
#!                  ███████╗███████╗██╗  ██╗██████╗  ██████╗
#!                  ╚══███╔╝██╔════╝██║  ██║██╔══██╗██╔════╝
#!                    ███╔╝ ███████╗███████║██████╔╝██║
#!                   ███╔╝  ╚════██║██╔══██║██╔══██╗██║
#!                  ███████╗███████║██║  ██║██║  ██║╚██████╗
#!                  ╚══════╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝
#!
#!                            - Made by Druxorey -
#!                         https://github.com/druxorey
#!
#! ========================================================================== !#

#* ================================= startup ================================ *#

[[ $- != *i* ]] && return
PS1='[\u@\h \W]\$ '
fastfetch --load-config ~/.config/fastfetch/init.jsonc && echo

eval "$(zoxide init zsh)"
eval "$(thefuck --alias)"
eval "$(oh-my-posh init zsh --config ~/.config/oh-my-posh/dracula.omp.json)"

#* =============================== path export ============================== *#

export PATH=$PATH:~/.local/bin
export CARGO_HOME='$XDG_DATA_HOME'/cargo
export GTK2_RC_FILES='$XDG_CONFIG_HOME'/gtk-2.0/gtkrc
export GIT_EDITOR=nvim
export EDITOR=nvim

#* ================================= aliases ================================ *#

# directory navigation
alias vim='nvim'
alias cat='bat'
alias fzf='fzf --preview "bat --color=always {}"'
alias ls='eza --icons --group-directories-first'
alias la='eza --icons -a --group-directories-first'
alias lt='eza --icons --tree --group-directories-first'
alias ll='eza --icons -alh --group-directories-first'
alias labc='eza --icons -la'
alias l.='eza -a | grep -E "^\."'
alias cd='z'
alias cdi='zi'
alias ..='z ..'
alias ...='z ../..'

# remaping
alias fk='fuck'
alias cp='cp -i'
alias th='trash'
alias thl='trash-list'
alias thr='trash-restore'
alias convert='magick'
alias grep='grep --color=auto'
alias matrix='cmatrix -C blue'
alias peaclock='peaclock --config ~/.config/peaclock'

# pacman and yay
alias sysupdate='sudo pacman -Syu ; yay -Sua --noconfirm; vencord'
alias unlock='sudo rm /var/lib/pacman/db.lck'

# git
alias gadd='git add'
alias gamend='git commit --amend'
alias gbranch='git branch -vv'
alias gcheckout='git checkout'
alias gclone='git clone'
alias gcommit='git commit -v'
alias gdiff='git diff'
alias gfetch='git fetch'
alias glog='git log --oneline --graph --decorate -n 10'
alias glogl='git log --oneline --graph --decorate'
alias gmerge='git merge --no-ff'
alias gpull='git pull'
alias gpush='git push'
alias greset='git reset'
alias grestore='git restore'
alias gstatus='git status -sb'
alias gvim='nvim -c "vertical Git" -c "wincmd h | q" '

# macros
alias copilot='nvim -c "CopilotChat" -c "wincmd h | q" '
alias cpv='rsync -avh --info=progress2'
alias mdtopdf='pandoc $1 -o default.pdf --pdf-engine=xelatex -V mainfont="Arial" monofont="Arial"'
alias todo='bspc rule -a "*" -o state=floating && kitty opdoc todo'
alias trans-es='trans -s english -t spanish'
alias setkeys='setxkbmap us -variant intl'
alias reload='clear && source ~/.zshrc'
alias yt-mp3='yt-dlp -x --audio-format mp3'
alias yt-1080='yt-dlp -f "bestvideo[height<=1080][ext=mp4]+bestaudio[ext=m4a]"'
alias yt-720='yt-dlp -f "bestvideo[height<=720][ext=mp4]+bestaudio[ext=m4a]"'
alias yt-480='yt-dlp -f "bestvideo[height<=480][ext=mp4]+bestaudio[ext=m4a]"'
alias vencord='sh -c "$(curl -sS https://raw.githubusercontent.com/Vendicated/VencordInstaller/main/install.sh)"'

# python
alias py='python3'
alias rm-pychache='sudo rm -r __pycache__'
alias venv-activate='source .venv/bin/activate'
alias venv-requirements='pip freeze > requirements.txt'
alias venv-create='virtualenv .venv'
alias venv-desactivate='deactivate'

# system
alias lock='dm-tool lock'
alias logout='bspc quit'
alias shutdown='shutdown now'

#* ================================ zsh setup =============================== *#

# plugins
source ~/.config/zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# autocomplete
zstyle :compinstall filename '/home/druxorey/.zshrc'
zstyle ':completion:*' menu select
zstyle ':autocomplete:*' default-context history-incremental-search-backward
_comp_options+=(globdots)
autoload -Uz compinit
compinit

# history
HISTFILE=~/.config/zsh/.histfile
HISTSIZE=10000
SAVEHIST=10000

# vim mode
bindkey -v
export KEYTIMEOUT=1

# key bindings
bindkey '^?'      backward-delete-char
bindkey '^u'      backward-kill-line
bindkey '^a'      beginning-of-line
bindkey '^e'      end-of-line
bindkey '^k'      kill-line
bindkey '^[[3~'   delete-char

# fzf settings
export FZF_ALT_C_OPTS='--preview "tree -C {} | head -200"'
export FZF_CTRL_T_OPTS="
  --walker-skip .git,node_modules,target,.local,.steam
  --preview 'bat -n --color=always {}'
  --bind 'ctrl-/:change-preview-window(down|hidden|)'"
source <(fzf --zsh)
source ~/.config/zsh/autocomplete-opdoc.sh

#* ================================ functions =============================== *#

function gfix() {
	echo "The commit: "
	git log --oneline --graph --decorate -n 1
	git reset --soft HEAD~1
	echo "\nWas restarted to previous commit: "
	git log --oneline --graph --decorate -n 1
}


function rsudo() {
    if [[ $# == 0 ]]; then
        sudo $(history -p '!!')
    else
        sudo '$@'
    fi
}


function compress() {

    [[ "$2" =~ ^[0-9]+$ ]] && set -- "$1" "" "$2"

    local date=$(date +%d-%m-%Y_%H-%M-%S)
    local compressionLevel="${3:-0}"
    local outputFile="${2:-${compressionLevel}_${date}.${1#*.}}"

    case $compressionLevel in
        0) compression=20 ;;
        1) compression=25 ;;
        2) compression=30 ;;
        3) compression=35 ;;
        *) echo 'Wrong compression level.' ; return ;;
    esac

    ffmpeg -i "$1" -vcodec libx264 -crf $compression "$outputFile"
}


function ex() {
    if [ -f "$1" ] ; then
        case $1 in
            *.tar.bz2)  xjf $1   ;;
            *.tar.gz)   tar xzf $1   ;;
            *.bz2)      bunzip2 $1   ;;
            *.rar)      unrar x $1   ;;
            *.gz)       gunzip $1    ;;
            *.tar)      tar xf $1    ;;
            *.tbz2)     tar xjf $1   ;;
            *.tgz)      tar xzf $1   ;;
            *.zip)      unzip $1     ;;
            *.Z)        uncompress $1;;
            *.7z)       7z x $1      ;;
            *.deb)      ar x $1      ;;
            *.tar.xz)   tar xf $1    ;;
            *.tar.zst)  unzstd $1    ;;
            *) echo '"$1" cannot be extracted via ex()' ;;
        esac
    else
        echo '"$1" is not a valid file'
    fi
}


function open() {
    if [ -f "$1" ] ; then
        case $1 in
            *.mp4)      mpv $1     ;;
            *.mkv)      mpv $1     ;;
            *.mp3)      mpv $1     ;;
            *.avi)      mpv $1     ;;
            *.flac)     mpv $1     ;;
            *.png)      sxiv $1    ;;
            *.webp)     sxiv $1    ;;
            *.jpeg)     sxiv $1    ;;
            *.jpg)      sxiv $1    ;;
            *.svg)      sxiv $1    ;;
            *.pdf)      zathura $1 ;;
            *) echo '"$1" cannot be open via open()\n Use: [mpv, sxiv or zathura]' ;;
        esac
    else
        echo '"$1" is not a valid file'
    fi
}


function hdmi-connect() {
	local resolution="${1:-1920x1080}"
	echo "Setting HDMI resolution to $resolution"
	xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1 --mode $resolution --rotate normal --right-of eDP-1
	bspc wm -r
}


function hdmi-disconnect() {
	echo "Turning off HDMI"
	xrandr --output HDMI-1 --off
}


function clean-obsidian() {
	local vaultPath="${HOME}/Documents/Obsidian"

	if [ ! -d "${vaultPath}/.git" ]; then
		echo "Error: Obsidian vault not found."
		return
	fi

	(
		cd "${vaultPath}" || { echo "Error: Failed to change directory."; return; }

		echo "Cleaning Obsidian vault..."

		git checkout --orphan temp_branch || { echo "Error: Failed to create orphan branch."; return; }
		git add -A || { echo "Error: Failed to add files."; return; }
		git commit -m "Initial commit" || { echo "Error: Failed to commit."; return; }
		git branch -D main || { echo "Error: Failed to delete main branch."; return; }
		git branch -m main || { echo "Error: Failed to rename branch to main."; return; }
		git push -f origin main || { echo "Error: Failed to push to origin."; return; }
	)
}
