#!/bin/bash

declare -r FORMAT_ERROR="\e[1;31m[ERROR]\e[0m"
declare -r COVER_PATH="$HOME/.local/share/lofi.jpg"

declare -a SOURCES=(
	"http://youtu.be/X4VbdwhkE10"
	"http://youtu.be/4xDzrJKXOOY"
	"http://youtu.be/JD-kMIpDfnY"
	"http://youtu.be/S_MOd40zlYU"
	"http://youtu.be/E2vONfzoyRI"
)

function help() {
	declare -r FORMAT_BOLD="\e[1;34m"
	declare -r FORMAT_RESET="\e[0m"
	echo -e "${FORMAT_BOLD}USAGE:${FORMAT_RESET} $(basename "$0") [OPTIONS] [VOLUME]

${FORMAT_BOLD}DESCRIPTION:${FORMAT_RESET}
    Streams random Lofi music from YouTube and visualizes it using cava.

${FORMAT_BOLD}ARGUMENTS:${FORMAT_RESET}
    VOLUME         Set the initial volume (0-100). Default: 50.

${FORMAT_BOLD}OPTIONS:${FORMAT_RESET}
    -d             Debug mode: Run in foreground and show output.
    -s SOURCE      Specify a custom YouTube URL to stream."

	return 0
}


function main() {
	local isDebug=false
	local source="${SOURCES[$RANDOM % ${#SOURCES[@]}]}"

	if ! command -v cava &> /dev/null; then
		printf "%b 'cava' is not installed.\n" "$FORMAT_ERROR"
		exit 1
	fi

	if ! command -v yt-dlp &> /dev/null; then
		printf "%b 'yt-dlp' tool is not installed.\n" "$FORMAT_ERROR"
		exit 1
	fi

	while getopts "hds:" opt; do
		case $opt in
			h) help && exit 0 ;;
			d) isDebug=true ;;
			s) source="$OPTARG" ;;
			*) printf "%b Try '%s -h' for more information.\n" "$FORMAT_ERROR" "$(basename "$0")" >&2 && exit 1 ;;
		esac
	done

	shift $((OPTIND - 1))

	if [[ ! -f "$COVER_PATH" ]]; then
		wget --output-document "$COVER_PATH" "https://f4.bcbits.com/img/a0591684555_10.jpg"
	fi

	local volume=$(echo "scale=2; ${1:-50} / 100" | bc)
	cp -f "$COVER_PATH" "/tmp/thumbnail.jpg"

	if $isDebug; then
		trap 'pkill -P $$ 2>/dev/null' EXIT SIGTERM SIGINT
		yt-dlp --format "ba/w" -o - "$source" | ffplay -nodisp -af "volume=$volume" - &
		wait
		exit 0
	fi

	(
		yt-dlp --format "ba/w" -o - "$source" | ffplay -nodisp -af "volume=$volume" -
	) > /dev/null 2>&1 &
    local PGID=$(ps -o pgid= -p $! | tr -d ' ')

	cava
    kill -TERM -"$PGID"

	return 0
}

main "$@"
