
# ============================ terminal ============================= #

# visual
background_opacity          1
window_margin_width         10

# fonts
font_size                   11.0

font_family                 Hack Nerd Font
bold_font                   Hack Nerd Font Bold
italic_font                 Hack Nerd Font Italic
bold_italic_font            Hack Nerd Font Bold Italic

# other
enable_audio_bell           no

# ========================== color scheme =========================== #

foreground                  #50FA7B
background                  #000000
selection_foreground        #ffffff
selection_background        #44475a

url_color                   #6A9475

# black
color0                      #21222c

# red
color1                      #ff5555

# green
color2                      #50fa7b

# yellow
color3                      #67C77F

# blue
color4                      #6A9475

# magenta
color5                      #6A9475

# cyan
color6                      #233327

# white
color7                      #f8f8f2

# Cursor colors
cursor                      #f8f8f2
cursor_text_color           background

# Tab bar colors
active_tab_foreground       #282a36
active_tab_background       #f8f8f2
inactive_tab_foreground     #282a36
inactive_tab_background     #6272a4

# Marks
mark1_foreground            #282a36
mark1_background            #ff5555

# Splits/Windows
active_border_color         #f8f8f2
inactive_border_color       #ffffff
