[mgr]
prepend_keymap = [
	{ on = [ "M", "m" ], run = "plugin gvfs -- select-then-mount", desc = "Select device then mount" },
	{ on = [ "M", "M" ], run = "plugin gvfs -- select-then-mount --jump", desc = "Select device to mount and jump to its mount point" },
	{ on = [ "M", "R" ], run = "plugin gvfs -- remount-current-cwd-device", desc = "Remount device under cwd" },
	{ on = [ "M", "u" ], run = "plugin gvfs -- select-then-unmount --eject", desc = "Select device then eject" },
	{ on = [ "M", "U" ], run = "plugin gvfs -- select-then-unmount --eject --force", desc = "Select device then force to eject/unmount" },
	{ on = [ "M", "a" ], run = "plugin gvfs -- add-mount", desc = "Add a GVFS mount URI" },
	{ on = [ "M", "e" ], run = "plugin gvfs -- edit-mount", desc = "Edit a GVFS mount URI" },
	{ on = [ "M", "r" ], run = "plugin gvfs -- remove-mount", desc = "Remove a GVFS mount URI" },
	{ on = [ "M", "o" ], run = "plugin mount" },
	{ on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device --automount", desc = "Automount then select device to jump to its mount point" },
	{ on = [ "c", "a", "a" ], run = "plugin compress", desc = "Archive selected files" },
	{ on = [ "c", "a", "p" ], run = "plugin compress -p", desc = "Archive selected files (password)" },
	{ on = [ "c", "a", "h" ], run = "plugin compress -ph", desc = "Archive selected files (password+header)" },
	{ on = [ "c", "a", "l" ], run = "plugin compress -l", desc = "Archive selected files (compression level)" },
	{ on = [ "c", "a", "u" ], run = "plugin compress -phl", desc = "Archive selected files (password+header+level)" },
	{ on = [ ">", "s" ], run = "plugin what-size", desc = "Calc size of selection or cwd" },
	{ on = [ ">", "e" ], run = "shell thunar .", desc = "Open thunar on cwd" },
	{ on = [ ">", "n" ], run = "shell nvim --block", desc = "Open nvim on cwd" },
]
