
;! ========================================================================== !;
;!
;!          ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;!          ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;!          ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;!          ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;!          ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;!          ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;!
;!                                  BORDERS
;!
;!                            - Made by Druxorey -
;!                         https://github.com/druxorey
;!
;! ========================================================================== !;

[module/RB]
type = custom/text
format = "%{O-1}%{T3} %{T-}%{O-11}"
format-foreground = ${theme.drx-color-surface}
format-background = ${theme.drx-color-base}

[module/LB]
type = custom/text
format = "%{T3} %{T-}%{O-1}"
format-foreground = ${theme.drx-color-surface}
format-background = ${theme.drx-color-base}

[module/MB]
type = custom/text
format = "  "
format-background = ${theme.drx-color-surface}

[module/MLB]
type = custom/script
exec = "~/.config/polybar/scripts/get-mic.sh left"
interval = 1

format = <label>
format-background = ${theme.drx-color-base}

label =  "%{T3} %output%%{T-}%{O-1}"
label-foreground = ${theme.drx-color-accent}

[module/MRB]
type = custom/script
exec = "~/.config/polybar/scripts/get-mic.sh right"
interval = 1

format = <label>
format-background = ${theme.drx-color-base}

label =  "%{O-1}%{T3}%output% %{T-}%{O-11}"
label-foreground = ${theme.drx-color-accent}
