;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;==========================================================

[colors]
background = #1f1f28
background-alt = #44475A
foreground = #F8F8F2
primary = #BD93F9
secondary = #FF79C6
alert = #FF5555
disabled = #44475A

;==========================================================

[settings]
screenchange-reload = true
pseudo-transparency = true

[bar/main-normal]
monitor = eDP-1
width = 100%
height = 24pt
radius = 10

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0pt

border-size = 4pt
border-bottom-size = 0pt
border-color = 

padding-left = 4
padding-right = 4

module-margin = 2

separator = |
separator-foreground = ${colors.disabled}

font-0 = NotoSans Nerd Font:size=11;2

modules-left = arch date  
modules-center = xworkspaces
modules-right = wlan battery pulseaudio 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

[bar/main-monocle]
monitor = eDP-1
width = 100%
height = 28pt
radius = 0

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 0pt

border-size = 0pt
border-bottom-size = 0pt
border-color = 

padding-left = 4
padding-right = 4

module-margin = 2

separator = |
separator-foreground = ${colors.disabled}

font-0 = NotoSans Nerd Font:size=11;2

modules-left = arch date  
modules-center = xworkspaces
modules-right = wlan battery pulseaudio 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true


;==========================================================

[module/arch]
type = custom/menu

label-open = "󰣇"
label-close = "󰣇"
label-separator = |
label-separator-foreground = ${colors.disabled}
format-spacing = 1

menu-0-0 = " Bluetooth"
menu-0-0-exec = blueman-manager &
menu-0-1 = " Power"
menu-0-1-exec = menu-open-1

menu-1-0 = "⏽ Shutdown"
menu-1-0-exec = systemctl poweroff
menu-1-1 = "⭘ Reboot"
menu-1-1-exec = systemctl reboot

;==========================================================

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-foreground = ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

;==========================================================

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume> <label-volume>

label-muted = "󰖁"
label-muted-foreground = #666

ramp-volume-0 = "󰕿"
ramp-volume-1 = "󰖀"
ramp-volume-2 = "󰕾"

;==========================================================

[network-base]
type = internal/network

format-connected-prefix = 
format-connected = 󰤨 <label-connected>
format-disconnected = %{A1:nmcli networking on:}󰤮%{A}

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{A1:nmcli networking off:}%essid%%{A}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

;==========================================================

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y/%m/%d %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

;==========================================================

[module/battery]
type = internal/battery

format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>

label-charging = %percentage%%
label-discharging = %percentage%%

ramp-capacity-0 = " " 
ramp-capacity-1 = " " 
ramp-capacity-2 = " " 
ramp-capacity-3 = " " 
ramp-capacity-4 = " " 

animation-charging-0 = " " 
animation-charging-1 = " " 
animation-charging-2 = " " 
animation-charging-3 = " " 
animation-charging-4 = " " 
animation-charging-framerate = 750

animation-discharging-0 = " " 
animation-discharging-1 = " " 
animation-discharging-2 = " " 
animation-discharging-3 = " " 
animation-discharging-4 = " " 
animation-discharging-framerate = 500
