
;! ========================================================================== !;
;!
;!          ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;!          ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;!          ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;!          ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;!          ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;!          ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;!
;!                                   MODULES
;!
;!                            - Made by Druxorey -
;!                         https://github.com/druxorey
;!
;! ========================================================================== !;

[module/arch]
type = custom/text

content = "󰣇"
click-left = sh ~/.config/rofi/scripts/power-rofi.sh

;* ========================================================================== *;

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt
group-by-monitor = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-foreground = ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = 
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

;* ========================================================================== *;

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume>  <label-volume>

label-muted = "󰖁"
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = "󰕿"
ramp-volume-1 = "󰖀"
ramp-volume-2 = "󰕾"

;* ========================================================================== *;

[network-base]
type = internal/network

format-connected = <label-connected>
format-disconnected = %{A1:sh ~/.config/rofi/scripts/wifi-rofi.sh:}󰤮%{A}

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = 󰤨  %{A1:sh ~/.config/rofi/scripts/wifi-rofi.sh:}%essid%%{A}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

;* ========================================================================== *;

[module/date]
type = internal/date
interval = 1

date =    %H:%M
date-alt =    %d/%m/%Y %H:%M:%S
label = %date%
label-foreground = ${colors.primary}

;* ========================================================================== *;

[module/battery]
type = internal/battery

format-full = 󱐋 
format-charging = <animation-charging>  <label-charging>
format-discharging = <ramp-capacity>  <label-discharging>

label-full = %percentage%
label-charging = %percentage%%
label-discharging = %percentage%%

ramp-capacity-0 = " " 
ramp-capacity-1 = " " 
ramp-capacity-2 = " " 
ramp-capacity-3 = " " 
ramp-capacity-4 = " " 

animation-charging-0 = " " 
animation-charging-1 = " " 
animation-charging-2 = " " 
animation-charging-3 = " " 
animation-charging-4 = " " 
animation-charging-framerate = 750

animation-discharging-0 = " " 
animation-discharging-1 = " " 
animation-discharging-2 = " " 
animation-discharging-3 = " " 
animation-discharging-4 = " " 
animation-discharging-framerate = 500
