
;! ========================================================================== !;
;!
;!          ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;!          ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;!          ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;!          ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;!          ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;!          ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;!
;!                                   MODULES
;!
;!                            - Made by Druxorey -
;!                         https://github.com/druxorey
;!
;! ========================================================================== !;

[module/cmus]
type = custom/script
exec = ~/.config/polybar/scripts/get-cmus.sh
click-left = cmus-remote -u
click-right = sh "$HOME/.config/rofi/scripts/panel_music.sh"
interval = 1

label = " %output% "

format = <label>
format-background = ${theme.drx-color-base-1}
format-foreground = ${theme.drx-color-text}

[module/arch]
type = custom/text
click-left = sh ~/.config/rofi/scripts/menu_start.sh polybar

label = " 󰣇 "

format = <label>
format-background = ${theme.drx-color-base-1}
format-foreground = ${theme.drx-color-accent}

[module/power]
type = custom/text
click-left = sh ~/.config/rofi/scripts/panel_power.sh polybar

label = " ⏻ "

format = <label>
format-background = ${theme.drx-color-base-1}
format-foreground = ${theme.drx-color-accent}

[module/get-processes]
type = custom/script
exec = ~/.config/polybar/scripts/get-processes.sh
click-left = sh ~/.config/polybar/scripts/kill-processes.sh
interval = 1

label = " %output%    "

format = <label>
format-background = ${theme.drx-color-base-1}
format-foreground = ${theme.drx-color-text}

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/get-bluetooth.sh
click-left = blueman-manager
interval = 1

label = " %output% "

format = <label>
format-background = ${theme.drx-color-base-1}
format-foreground = ${theme.drx-color-text}

[module/windows]
type = custom/script
exec = ~/.config/polybar/scripts/get-windows.sh
click-left = bspc node -f next.local.window
click-right = bspc node -f prev.local.window
interval = 1

label = "    󱂬  %output% "

format = <label>
format-background = ${theme.drx-color-base-1}
format-foreground = ${theme.drx-color-text}

[module/github]
type = internal/github

token = ${file:/home/druxorey/.local/share/github/access.token}
user = druxorey
interval = 10
api-url = https://api.github.com/

label = "       %notifications% "

format = <label>
format-background = ${theme.drx-color-base-1}
format-foreground = ${theme.drx-color-text}

format-offline = ""

;* ========================================================================== *;

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt
group-by-monitor = true

[module/xworkspaces]
type = internal/xworkspaces

label-active = 󰮯
label-active-foreground = ${theme.drx-color-accent}
label-active-background = ${theme.drx-color-base-1}
label-active-padding = 1

label-occupied = 󰊠
label-occupied-foreground = ${theme.drx-color-text}
label-occupied-background = ${theme.drx-color-base-1}
label-occupied-padding = 1

label-urgent = %name%
label-urgent-foreground = ${theme.drx-color-text}
label-urgent-background = ${theme.drx-color-alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${theme.drx-color-deactivate}
label-empty-background = ${theme.drx-color-base-1}
label-empty-padding = 1

;* ========================================================================== *;

[module/pulseaudio]
type = internal/pulseaudio

format-volume = "<ramp-volume>   <label-volume>"
format-volume-background = ${theme.drx-color-base-1}
format-volume-foreground = ${theme.drx-color-text}

label-volume = "%percentage%% "

label-muted = "󰖁"
label-muted-foreground = ${theme.drx-color-deactivate}
label-muted-background = ${theme.drx-color-base-1}

ramp-volume-0 = "󰕿"
ramp-volume-1 = "󰖀"
ramp-volume-2 = "󰖀"
ramp-volume-3 = "󰖀"
ramp-volume-4 = "󰕾"
ramp-volume-5 = "󰕾"

;* ========================================================================== *;

[network-base]
type = internal/network

format-connected ="<ramp-signal>  <label-connected>"
format-connected-background = ${theme.drx-color-base-1}

format-disconnected = <label-disconnected>
format-disconnected-background = ${theme.drx-color-base-1}

ramp-signal-0 = "󰤯 "
ramp-signal-1 = "󰤟 "
ramp-signal-2 = "󰤢 "
ramp-signal-3 = "󰤥 "
ramp-signal-4 = "󰤨 "
ramp-signal-5 = "󰤨 "

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{A1:sh ~/.config/rofi/scripts/panel_wifi.sh polybar:}%essid% %{A}

label-disconnected = %{A1:sh ~/.config/rofi/scripts/panel_wifi.sh polybar:}󰤮 %{A}
label-disconnected-foreground = ${theme.drx-color-deactivate}

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

;* ========================================================================== *;

[module/date]
type = internal/date
interval = 1

date = "%H:%M"
date-alt = "%d/%m/%Y %H:%M:%S"

label = "   %date% "
label-foreground = ${theme.drx-color-text}
label-background = ${theme.drx-color-base-1}

;* ========================================================================== *;

[module/battery]
type = internal/battery

format-full = "󱐋"
format-full-background = ${theme.drx-color-base-1}
format-full-foreground = ${theme.drx-color-text}

format-charging ="<animation-charging>   <label-charging>"
format-charging-background = ${theme.drx-color-base-1}
format-charging-foreground = ${theme.drx-color-text}

format-discharging ="<ramp-capacity>   <label-discharging>"
format-discharging-background = ${theme.drx-color-base-1}
format-discharging-foreground = ${theme.drx-color-text}

label-full = %{A1:sh ~/.config/rofi/scripts/panel_energy.sh:}%percentage%% %{A}
label-charging = %{A1:sh ~/.config/rofi/scripts/panel_energy.sh:}%percentage%% %{A}
label-discharging = %{A1:sh ~/.config/rofi/scripts/panel_energy.sh:}%percentage%% %{A}

animation-charging-0 = "󱐋󰁺"
animation-charging-1 = "󱐋󰁼"
animation-charging-2 = "󱐋󰁾"
animation-charging-3 = "󱐋󰂀"
animation-charging-4 = "󱐋󰂂"
animation-charging-5 = "󱐋󰁹"
animation-charging-framerate = 500

ramp-capacity-0 = "󰁺"
ramp-capacity-1 = "󰁻"
ramp-capacity-2 = "󰁼"
ramp-capacity-3 = "󰁽"
ramp-capacity-4 = "󰁾"
ramp-capacity-5 = "󰁿"
ramp-capacity-6 = "󰂀"
ramp-capacity-7 = "󰂁"
ramp-capacity-8 = "󰂂"
ramp-capacity-9 = "󰁹"
ramp-capacity-10 = "󰂄"
